name: theapp
description: "Helping hearts in Belgium."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  onesignal_flutter: ^5.1.2
  image_picker: ^1.1.1  
  flutter_localizations:
    sdk: flutter
  intl: any
  http: ^1.2.1
  dotted_border: ^2.1.0
  provider: ^6.1.2
  font_awesome_flutter: ^10.7.0
  permission_handler: ^11.3.1
  video_player: ^2.8.6
  chewie: ^1.2.2
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0
  cloudinary_public: ^0.23.1
  flutter_svg: ^2.0.10+1
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  geolocator: ^11.0.0
  location: ^6.0.1
  flutter_rating_bar: ^4.0.1
  flutter_time_picker_spinner: ^2.0.0
  mailer: ^6.1.0
  google_maps_flutter: ^2.6.1
  geocoding: ^3.0.0
  url_launcher: ^6.2.6
  web_socket_channel: ^3.0.0
  blur: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/dutch_flag.png
    - assets/images/english_flag.png
    - assets/images/header_login.png
    - assets/images/background_header_login.png
    - assets/images/heart.png
    - assets/videos/aed.mp4
    - assets/videos/bewustzijn_ademhaling_controleren.mp4
    - assets/videos/cpr.mp4
    - assets/videos/stabiele_zijligging.mp4
    - assets/images/thumbnails/aed.png
    - assets/images/thumbnails/bewustzijn.png
    - assets/images/thumbnails/cpr.png
    - assets/images/thumbnails/zijligging.png
    - assets/images/ambu.svg
    - assets/images/weels.svg
    - assets/images/person.png
    - assets/images/ehbokit.png
    - assets/images/emergency_heart.svg
    - assets/images/heart_minus.svg
    - assets/images/heart_check.svg
    - .env
    - lang/en.json
    - lang/nl.json
  fonts:
  - family: Comfortaa
    fonts:
      - asset: fonts/Comfortaa-Regular.ttf
        weight: 400
        style: normal
      - asset: fonts/Comfortaa-Bold.ttf
        weight: 700
        style: normal
      - asset: fonts/Comfortaa-Light.ttf
        weight: 300
        style: normal
      - asset: fonts/Comfortaa-Medium.ttf
        weight: 500
        style: normal
      - asset: fonts/Comfortaa-SemiBold.ttf
        weight: 600
        style: normal
  - family: Proxima-Soft
    fonts:
      - asset: fonts/ProximaSoft-Black.ttf
        weight: 800
        style: normal
      - asset: fonts/ProximaSoft-BlackIt.ttf
        weight: 800
        style: italic
      - asset: fonts/ProximaSoft-Bold.ttf
        weight: 700
        style: normal
      - asset: fonts/ProximaSoft-BoldIt.ttf
        weight: 700
        style: italic
      - asset: fonts/ProximaSoft-ExtraBold.ttf
        weight: 600
        style: normal
      - asset: fonts/ProximaSoft-ExtraBoldIt.ttf
        weight: 600
        style: italic
      - asset: fonts/ProximaSoft-SemiBold.ttf
        weight: 500
        style: normal
      - asset: fonts/ProximaSoft-SemiBoldIt.ttf
        weight: 500
        style: italic
      - asset: fonts/ProximaSoft-Medium.ttf
        weight: 400
        style: normal
      - asset: fonts/ProximaSoft-MediumIt.ttf
        weight: 400
        style: italic
      - asset: fonts/ProximaSoft-Regular.ttf
        weight: 300
        style: normal
      - asset: fonts/ProximaSoft-RegularIt.ttf
        weight: 300
        style: italic
      - asset: fonts/ProximaSoft-Light.ttf
        weight: 200
        style: normal
      - asset: fonts/ProximaSoft-LightIt.ttf
        weight: 200
        style: italic
      - asset: fonts/ProximaSoft-Thin.ttf
        weight: 100
        style: normal
      - asset: fonts/ProximaSoft-ThinIt.ttf
        weight: 100
        style: italic
        