name: theapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

fonts:
  - family: Comfortaa
    fonts:
      - asset: fonts/comfortaa/Comfortaa-Regular.ttf
        weight: 400
        style: normal
      - asset: fonts/comfortaa/Comfortaa-Bold.ttf
        weight: 700
        style: normal
      - asset: fonts/comfortaa/Comfortaa-Light.ttf
        weight: 300
        style: normal
      - asset: fonts/comfortaa/Comfortaa-Medium.ttf
        weight: 500
        style: normal
      - asset: fonts/comfortaa/Comfortaa-SemiBold.ttf
        weight: 600
        style: normal
  - family: Proxima Soft
    fonts:
      - asset: fonts/proxima-soft/ProximaSoft-Black.ttf
        weight: 800
        style: normal
      - asset: fonts/proxima-soft/ProximaSoft-BlackIt.ttf
        weight: 800
        style: italic
      - asset: fonts/proxima-soft/ProximaSoft-Bold.ttf
        weight: 700
        style: normal
      - asset: fonts/proxima-soft/ProximaSoft-BoldIt.ttf
        weight: 700
        style: italic
      - asset: fonts/proxima-soft/ProximaSoft-ExtraBold.ttf
        weight: 600
        style: normal
      - asset: fonts/proxima-soft/ProximaSoft-ExtraBoldIt.ttf
        weight: 600
        style: italic
      - asset: fonts/proxima-soft/ProximaSoft-SemiBold.ttf
        weight: 500
        style: normal
      - asset: fonts/proxima-soft/ProximaSoft-SemiBoldIt.ttf
        weight: 500
        style: italic
      - asset: fonts/proxima-soft/ProximaSoft-Medium.ttf
        weight: 400
        style: normal
      - asset: fonts/proxima-soft/ProximaSoft-MediumIt.ttf
        weight: 400
        style: italic
      - asset: fonts/proxima-soft/ProximaSoft-Regular.ttf
        weight: 300
        style: normal
      - asset: fonts/proxima-soft/ProximaSoft-RegularIt.ttf
        weight: 300
        style: italic
      - asset: fonts/proxima-soft/ProximaSoft-Light.ttf
        weight: 200
        style: normal
      - asset: fonts/proxima-soft/ProximaSoft-LightIt.ttf
        weight: 200
        style: italic
      - asset: fonts/proxima-soft/ProximaSoft-Thin.ttf
        weight: 100
        style: normal
      - asset: fonts/proxima-soft/ProximaSoft-ThinIt.ttf
        weight: 100
        style: italic
        